import type { Metadata } from "next";
import { inter, lusitana, roboto, robotoMono, ubuntuFont } from '@/app/ui/fonts';
import "./globals.css";
import Navbar from "../components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${roboto.className} antialiased`}>
        {/* Navbar */}
        <div className="mb-10">
          <Navbar />
        </div>
        {children}</body>
    </html>
  );
}
